### ISSUE TITLE
Fail to start filesystem in test_mdt0_undeletable() with lustre 2.10.50

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#108]
kernel version: 3.10.0-514.21.1.el7_lustre.x86_64
lustre version: 2.10.0_RC1-1.el7
OS: CentOS Linux release 7.3.1611 (Core)

Failure consistently occurs in *test_filesystem_dne.py test_md0_undeleteable()* during SSI runs with lustre 2.10.50

This is the only test we have which creates a filesystem with 3 MDTs

On recreating LFS in a similar configuration with mgs, 3*mdts and 1 ost through IML, all other targets mount commands return successfully but ost mount command never returns.
During when the MDT mount commands are being issued, lots of activity in the kernel messages log including multiple LustreErrors and stack traces, warnings of high cpu usage and then  
```
kernel:NMI watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [lwp_notify_fs1-:13630]
```
This is on a LDISKF only fs with DNE enabled. The OST mount command used is as follows and the MDT mount commands are of a similar format:
```
mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk5 /mnt/fs1-OST0000
```

The following gists show excerpts from the */var/log/messages* log during instances of this type of failure (MDT mounting in DNE):

https://gist.github.com/tanabarr/1adb35a7e7da2581be79df8f45417411
https://gist.github.com/tanabarr/70d3bfa66c4fc474b82c7c02adcda511
https://gist.github.com/tanabarr/9f54584621aacfdeb3899f59687cb918

The last gist link is an extended excerpt giving more contextual log information regarding the attempted mounting of the MDTs and the subsequent CPU load warnings. The entire logfile is attached to this issue in the comments.

----
Details of failed IML SSI test run:

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/521/arch=x86_64,distro=el7//consoleFull

```test_mdt0_undeletable (tests.integration.shared_storage_configuration.test_filesystem_dne.TestFilesystemDNE) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py", line 189, in test_mdt0_undeletable
    filesystem = self._create_filesystem(3)
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_filesystem_dne.py", line 69, in _create_filesystem
    'conf_params': {}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 432, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/', u'/api/job/44/', u'/api/job/45/', u'/api/job/46/', u'/api/job/47/', u'/api/job/48/', u'/api/job/49/'], u'complete': True, u'created_at': u'2017-06-28T13:01:16.850523+00:00', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': u'9', 
```

**Comment by tanabarr** [comment]
relevant logs from agent which is mounting target 

[chroma-agent.log.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1113164/chroma-agent.log.txt)
[chroma-agent-console.log.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1113168/chroma-agent-console.log.txt)
[messages.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1113171/messages.txt)
[yum.log.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1113174/yum.log.txt)

and from IML manager, orchestrating file system creation

[job_scheduler.log.txt](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1113175/job_scheduler.log.txt)

**Comment by tanabarr** [comment]
another example of SSI run which just fails on the test_md0_undeletable test: http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/559/arch=x86_64,distro=el7/

**Comment by tanabarr** [comment]
https://jira.hpdd.intel.com/LU-9725
relate to this failing test
