### ISSUE TITLE
Directory not empty: 'simulator_state_TestShutdownAndReboot.test_server_shutdown_2017-07-13_075933'

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#150]
In an SSI-simulator [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration-with-simulator/545/distro=el7,type=master):

```
test_server_shutdown (tests.integration.shared_storage_configuration.test_shutdown_reboot.TestShutdownAndReboot) ... ERROR
ERROR
Traceback (most recent call last):
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 183, in tearDown
    shutil.rmtree(self.simulator.folder)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'simulator_state_TestShutdownAndReboot.test_server_shutdown_2017-07-13_075933'
```

**Comment by brianjmurrell** [comment]
[Another]{http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration-with-simulator/541/distro=el7,type=master)

**Comment by jgrund** [comment]
Sim has been removed.
