### ISSUE TITLE
failure in register_simulated_hosts

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#154]
In a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration-with-simulator/558/distro=el7,type=master):

```
test_create_filesystem_with_failover_oss_chroma_controlled (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 132, in test_create_filesystem_with_failover_oss_chroma_controlled
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 14, in _test_create_filesystem_with_failover
    filesystem_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 265, in _add_hosts
    self.register_simulated_hosts(addresses)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 260, in register_simulated_hosts
    self.wait_for_commands(self.chroma_manager, host_create_command_ids.values())
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/2297/', u'/api/job/2298/', u'/api/job/2299/', u'/api/job/2300/', u'/api/job/2301/', u'/api/job/2302/', u'/api/job/2303/', u'/api/job/2304/', u'/api/job/2305/', u'/api/job/2306/', u'/api/job/2307/'], u'complete': True, u'created_at': u'2017-07-13T23:07:41.619223+00:00', u'message': u'Deploying agent to host test001', u'cancelled': True, u'errored': False, u'resource_uri': u'/api/command/582/', u'id': u'582', u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
COMMAND 582: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/2297/', u'/api/job/2298/', u'/api/job/2299/', u'/api/job/2300/', u'/api/job/2301/', u'/api/job/2302/', u'/api/job/2303/', u'/api/job/2304/', u'/api/job/2305/', u'/api/job/2306/', u'/api/job/2307/'], u'complete': True, u'created_at': u'2017-07-13T23:07:41.619223+00:00', u'message': u'Deploying agent to host test001', u'cancelled': True, u'errored': False, u'resource_uri': u'/api/command/582/', u'id': u'582', u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}


--------------------- >> end captured stdout << ----------------------
```

**Comment by jgrund** [comment]
Simulator has been removed.
