### ISSUE TITLE
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#212]
In a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/907/arch=x86_64,distro=el7):

```
test_alerts (tests.integration.shared_storage_configuration.test_alerting.TestAlerting) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 37, in test_alerts
    fs_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 206, in set_host_profiles
    'objects': [{'host': h['id'], 'profile': self.get_best_host_profile(h['address'])['name']} for h in hosts]
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 54, in get_best_host_profile
    host_validations = self.get_valid_host_validations(host).profiles
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 114, in get_valid_host_validations
    self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 173, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion))
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

Assertion False is not true
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/971/arch=x86_64,distro=el7):

```
test_alerts (tests.integration.shared_storage_configuration.test_alerting.TestAlerting) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 37, in test_alerts
    fs_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 206, in set_host_profiles
    'objects': [{'host': h['id'], 'profile': self.get_best_host_profile(h['address'])['name']} for h in hosts]
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 54, in get_best_host_profile
    host_validations = self.get_valid_host_validations(host).profiles
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 114, in get_valid_host_validations
    self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 173, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion))
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

Assertion False is not true
```

**Comment by brianjmurrell** [comment]
[Another here](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-existing-filesystem-configuration/760/arch=x86_64,distro=el7):

```
test_filesystem_detection_verify_mountable (tests.integration.existing_filesystem_configuration.test_filesystem_detection.TestFilesystemDetection) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/test_filesystem_detection.py", line 170, in test_filesystem_detection_verify_mountable
    self._detect_filesystem()
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/test_filesystem_detection.py", line 27, in _detect_filesystem
    self.add_hosts([l['address'] for l in config['lustre_servers']])
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 206, in set_host_profiles
    'objects': [{'host': h['id'], 'profile': self.get_best_host_profile(h['address'])['name']} for h in hosts]
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 54, in get_best_host_profile
    host_validations = self.get_valid_host_validations(host).profiles
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 114, in get_valid_host_validations
    self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 173, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion))
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

Assertion False is not true
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-existing-filesystem-configuration/835/arch=x86_64,distro=el7/):

```
test_filesystem_detection_verify_mountable (tests.integration.existing_filesystem_configuration.test_filesystem_detection.TestFilesystemDetection) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/test_filesystem_detection.py", line 170, in test_filesystem_detection_verify_mountable
    self._detect_filesystem()
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/test_filesystem_detection.py", line 27, in _detect_filesystem
    self.add_hosts([l['address'] for l in config['lustre_servers']])
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 206, in set_host_profiles
    'objects': [{'host': h['id'], 'profile': self.get_best_host_profile(h['address'])['name']} for h in hosts]
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 54, in get_best_host_profile
    host_validations = self.get_valid_host_validations(host).profiles
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 114, in get_valid_host_validations
    self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 173, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion))
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

Assertion False is not true
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1111/arch=x86_64,distro=el7)

**Comment by brianjmurrell** [comment]
All occurrences seem to be rooted in what is effectively #142 so perhaps #142 is introducing this failure.  But really that stack is only about automating the configuration of repositories.  I'll look into that patch stack more deeply.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1171) on master now (probably due to #142 landing):

```
test_create_filesystem_with_failover_oss_chroma_controlled (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 134, in test_create_filesystem_with_failover_oss_chroma_controlled
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 15, in _test_create_filesystem_with_failover
    filesystem_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 206, in set_host_profiles
    'objects': [{'host': h['id'], 'profile': self.get_best_host_profile(h['address'])['name']} for h in hosts]
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 54, in get_best_host_profile
    host_validations = self.get_valid_host_validations(host).profiles
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 114, in get_valid_host_validations
    self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 173, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion))
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertTrue(self.get_host_validations(host).valid))

Assertion False is not true
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1214)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1217/consoleFull)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1219)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1227)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1229)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1246)
