### ISSUE TITLE
AssertionError: {u'power_control': 1503014518, u'stats': 1503014518, u'gunicorn': 1503014518, u' [truncated]... != {u'power_control': 1503014518, u'stats': 1503014518, u'gunicorn': 1503014518, u' [truncated]...

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#220]
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/948:
```
test_same_name (tests.integration.shared_storage_configuration.test_filesystem_same_name.TestFilesystemSameNameHYD832) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 201, in tearDown
    self.get_supervisor_controlled_process_start_times())
AssertionError: {u'power_control': 1503014518, u'stats': 1503014518, u'gunicorn': 1503014518, u' [truncated]... != {u'power_control': 1503014518, u'stats': 1503014518, u'gunicorn': 1503014518, u' [truncated]...
- {u'corosync': 1503014518,
?                     - ^^

+ {u'corosync': 1503015300,
?                      ^^^

   u'gunicorn': 1503014518,
   u'http_agent': 1503014518,
   u'job_scheduler': 1503014518,
   u'lustre_audit': 1503014518,
   u'plugin_runner': 1503014518,
   u'power_control': 1503014518,
   u'realtime': 1503014518,
   u'stats': 1503014518,
   u'syslog': 1503014518,
   u'view_server': 1503014518}
-------------------- >> begin captured stdout << ---------------------
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2677/arch=x86_64,distro=el7):

```
testUpdateNids (tests.integration.shared_storage_configuration.test_writeconf.TestWriteconf) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 209, in tearDown
    self.get_supervisor_controlled_process_start_times())
AssertionError: {u'power_control': 1511618113, u'stats': 1511618113, u'gunicorn': 1511618113, u' [truncated]... != {u'power_control': 1511618113, u'stats': 1511618113, u'gunicorn': 1511618113, u' [truncated]...
  {u'corosync': 1511618113,
   u'gunicorn': 1511618113,
   u'http_agent': 1511618113,
   u'job_scheduler': 1511618113,
   u'lustre_audit': 1511618113,
   u'plugin_runner': 1511618113,
   u'power_control': 1511618113,
   u'realtime': 1511618113,
   u'stats': 1511618113,
   u'syslog': 1511618113,
-  u'view_server': 1511618113}
?                          ^^

+  u'view_server': 1511618717}
?                         + ^

-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 3, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 4, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 3, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 4, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 3, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 4, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/23/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 3, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 4, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 3, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 4, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 3, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'host_id': 4, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 3, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 4, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 3, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'host_id': 4, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/23/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 3, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 4, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-41vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-41vm16.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 3, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-41vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'host_id': 4, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-41vm18.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10672993730'}

--------------------- >> end captured stdout << ----------------------
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2678/arch=x86_64,distro=el7).
