### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by jinho40** [intel-hpdd/intel-manager-for-lustre#252]
### Description 

A short description of your issue
IEEL4 Preview Installation Problem

Hello
This is the problem with creating a file system after installation in the IML 4 Preview 2.
Maybe MGT is not created because it is not created. Can I confirm it?
The following logs occur when you press the MGT START button at IML.
Thanks.

```
[2017-08-30 04:22:26,086: INFO/job] AlertState: Raised <class 'chroma_core.models.command.CommandRunningAlert'> on Command object at severity 20
[2017-08-30 04:22:26,089: INFO/command_plan] set_state: <class 'chroma_core.models.target.ManagedTarget'>-20 transitioning from unformatted to mounted
[2017-08-30 04:22:26,183: INFO/command_plan] Created command 113 (Start target MGS) with 4 jobs
[2017-08-30 04:22:26,228: INFO/job_scheduler] run_next: 1 runnable jobs of (4 pending, 0 tasked)
[2017-08-30 04:22:26,366: INFO/job] create_parameters: host: 'mds1' active_volume_node: 'TargetVolumeInfo(host=<ManagedHost: mds1>, path=u'/dev/disk/by-id/scsi-36001405f1b357060eef49ea8b7e5640f', device_type='linux')'
[2017-08-30 04:22:26,383: ERROR/job_scheduler] Job 566: exception in get_steps: Traceback (most recent call last):
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 533, in _check_jobs
File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1353, in get_steps
File "/usr/share/chroma-manager/chroma_core/models/target.py", line 146, in get_failover_nids
AssertionError
[2017-08-30 04:22:26,383: INFO/job_scheduler] Job 566 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,418: INFO/job_scheduler] run_next: 1 runnable jobs of (3 pending, 0 tasked)
[2017-08-30 04:22:26,431: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['formatted'] (preferred formatted)
[2017-08-30 04:22:26,451: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['formatted'] (preferred formatted)
[2017-08-30 04:22:26,452: WARNING/job_scheduler] Job 567: cancelling because of failed dependency
[2017-08-30 04:22:26,452: INFO/job_scheduler] Job 567 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,492: INFO/job_scheduler] run_next: 1 runnable jobs of (2 pending, 0 tasked)
[2017-08-30 04:22:26,576: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['registered'] (preferred registered)
[2017-08-30 04:22:26,610: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['registered'] (preferred registered)
[2017-08-30 04:22:26,610: WARNING/job_scheduler] Job 568: cancelling because of failed dependency
[2017-08-30 04:22:26,610: INFO/job_scheduler] Job 568 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,665: INFO/job_scheduler] run_next: 1 runnable jobs of (1 pending, 0 tasked)
[2017-08-30 04:22:26,685: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['unmounted'] (preferred unmounted)
[2017-08-30 04:22:26,710: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['unmounted'] (preferred unmounted)
[2017-08-30 04:22:26,710: WARNING/job_scheduler] Job 569: cancelling because of failed dependency
[2017-08-30 04:22:26,710: INFO/job_scheduler] Job 569 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,792: INFO/job_scheduler] run_next: 0 runnable jobs of (0 pending, 0 tasked)
```

### Repro

What steps were taken leading to this issue

### Version

What version of IML? IML4 Preview 2
What Operating System? CentOS
What Operating System version? 7.3

**Comment by jinho40** [comment]
Add the log.
---------------------------------------------------------------------------------------------------------------------
[2017-08-30 04:22:26,086: INFO/job] AlertState: Raised <class 'chroma_core.models.command.CommandRunningAlert'> on Command object at severity 20
[2017-08-30 04:22:26,089: INFO/command_plan] set_state: <class 'chroma_core.models.target.ManagedTarget'>-20 transitioning from unformatted to mounted
[2017-08-30 04:22:26,183: INFO/command_plan] Created command 113 (Start target MGS) with 4 jobs
[2017-08-30 04:22:26,228: INFO/job_scheduler] run_next: 1 runnable jobs of (4 pending, 0 tasked)
[2017-08-30 04:22:26,366: INFO/job] create_parameters: host: 'mds1' active_volume_node: 'TargetVolumeInfo(host=<ManagedHost: mds1>, path=u'/dev/disk/by-id/scsi-36001405f1b357060eef49ea8b7e5640f', device_type='linux')'
[2017-08-30 04:22:26,383: ERROR/job_scheduler] Job 566: exception in get_steps: Traceback (most recent call last):
File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 533, in _check_jobs
File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1353, in get_steps
File "/usr/share/chroma-manager/chroma_core/models/target.py", line 146, in get_failover_nids
AssertionError
[2017-08-30 04:22:26,383: INFO/job_scheduler] Job 566 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,418: INFO/job_scheduler] run_next: 1 runnable jobs of (3 pending, 0 tasked)
[2017-08-30 04:22:26,431: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['formatted'] (preferred formatted)
[2017-08-30 04:22:26,451: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['formatted'] (preferred formatted)
[2017-08-30 04:22:26,452: WARNING/job_scheduler] Job 567: cancelling because of failed dependency
[2017-08-30 04:22:26,452: INFO/job_scheduler] Job 567 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,492: INFO/job_scheduler] run_next: 1 runnable jobs of (2 pending, 0 tasked)
[2017-08-30 04:22:26,576: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['registered'] (preferred registered)
[2017-08-30 04:22:26,610: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['registered'] (preferred registered)
[2017-08-30 04:22:26,610: WARNING/job_scheduler] Job 568: cancelling because of failed dependency
[2017-08-30 04:22:26,610: INFO/job_scheduler] Job 568 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,665: INFO/job_scheduler] run_next: 1 runnable jobs of (1 pending, 0 tasked)
[2017-08-30 04:22:26,685: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['unmounted'] (preferred unmounted)
[2017-08-30 04:22:26,710: WARNING/job] DependOn not satisfied: MGS in state unformatted, not one of ['unmounted'] (preferred unmounted)
[2017-08-30 04:22:26,710: WARNING/job_scheduler] Job 569: cancelling because of failed dependency
[2017-08-30 04:22:26,710: INFO/job_scheduler] Job 569 completing (errored=False, cancelled=True)
[2017-08-30 04:22:26,792: INFO/job_scheduler] run_next: 0 runnable jobs of (0 pending, 0 tasked)

**Comment by jinho40** [comment]
additional information 

I used Vm on Xenserver and ISCSI share volume.

The same is not installed in the Preview 3 version.

**Comment by jgrund** [comment]
@jinho40 thanks for the report. Can you confirm you've tested this with Preview 3 and had the same behavior?

**Comment by jinho40** [comment]
The above is probably an issue with iscsi on my VM.

**Comment by jinho40** [comment]
I’m sorry for the lately reply

Installation is good in the new version

You can close this

Thanks.


2018. 3. 9. 오전 9:21, stale[bot] <notifications@github.com> 작성:
