### ISSUE TITLE
backtrace: Failed to register host lotus-9vm18.lotus.hpdd.lab.intel.com: rc=1

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#266]
[In](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1210):

```
test_alerts (tests.integration.shared_storage_configuration.test_alerting.TestAlerting) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 37, in test_alerts
    fs_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 268, in _add_hosts
    self.deploy_agents(addresses, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 199, in deploy_agents
    self.wait_for_commands(self.chroma_manager, command_ids)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/8/'], u'complete': True, u'created_at': u'2017-09-05T04:14:28.054589', u'message': u'Deploying agent to host lotus-9vm18.lotus.hpdd.lab.intel.com', u'cancelled': False, u'errored': True, u'resource_uri': u'/api/command/8/', u'id': 8, u'logs': u''}
-------------------- >> begin captured stdout << ---------------------
COMMAND 8: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/8/'], u'complete': True, u'created_at': u'2017-09-05T04:14:28.054589', u'message': u'Deploying agent to host lotus-9vm18.lotus.hpdd.lab.intel.com', u'cancelled': False, u'errored': True, u'resource_uri': u'/api/command/8/', u'id': 8, u'logs': u''}

Job 8 Errored (Deploying agent to lotus-9vm18.lotus.hpdd.lab.intel.com):
{u'commands': [u'/api/command/8/'], u'write_locks': [{u'locked_item_content_type_id': 65, u'locked_item_id': 4, u'locked_item_uri': u'/api/host/4/', u'resource_uri': u''}], u'description': u'Deploying agent to lotus-9vm18.lotus.hpdd.lab.intel.com', u'read_locks': [], u'class_name': u'DeployHostJob', u'step_results': {u'/api/step/8/': None}, u'created_at': u'2017-09-05T04:14:28.079800', u'modified_at': u'2017-09-05T04:14:28.079767', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/8/'], u'cancelled': False, u'errored': True, u'wait_for': [], u'id': 8, u'resource_uri': u'/api/job/8/'}

Step 8 failed:
step_count: 1
console: 
description: DeployStep: {'token': <RegistrationToken: RegistrationToken object>, 'profile_name': u'default', 'host': <ManagedHost: lotus-9vm18.lotus.hpdd.lab.intel.com>}
class_name: DeployStep
backtrace: Failed to register host lotus-9vm18.lotus.hpdd.lab.intel.com: rc=1
''
'  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8917    0  8917    0     0  95958      0 --:--:-- --:--:-- --:--:-- 95881
'
created_at: 2017-09-05T04:14:28.191396
args: {u'host': u'lotus-9vm18.lotus.hpdd.lab.intel.com', u'profile_name': u'default', u'token': u'RegistrationToken object'}
modified_at: 2017-09-05T04:16:31.122370
step_index: 0
state: failed
result: 
resource_uri: /api/step/8/
id: 8
log: 


--------------------- >> end captured stdout << ----------------------
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1230)

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1230) x2.
