### ISSUE TITLE
mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: No such file or directory

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#272]
[In](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1243):

```
test_lnet_reverse_dependencies (tests.integration.shared_storage_configuration.test_lnet_functionality.TestLNetFunctionality) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_lnet_functionality.py", line 18, in setUp
    self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 368, in create_filesystem_standard
    'conf_params': {}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 432, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/57/', u'/api/job/58/', u'/api/job/59/', u'/api/job/60/', u'/api/job/61/', u'/api/job/62/', u'/api/job/63/', u'/api/job/64/', u'/api/job/65/', u'/api/job/66/', u'/api/job/67/', u'/api/job/68/', u'/api/job/69/', u'/api/job/70/', u'/api/job/71/', u'/api/job/72/', u'/api/job/73/'], u'complete': True, u'created_at': u'2017-09-07T16:08:50.235897', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/17/', u'id': 17, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/25/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 4, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 3, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 4, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 3, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/22/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 4, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 3, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/23/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 4, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 3, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 4, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 3, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/25/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 4, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 3, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 4, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 3, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/22/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 4, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 3, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/23/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 4, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 3, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 4, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-48vm18.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 3, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-48vm17.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-48vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-48vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
COMMAND 17: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/57/', u'/api/job/58/', u'/api/job/59/', u'/api/job/60/', u'/api/job/61/', u'/api/job/62/', u'/api/job/63/', u'/api/job/64/', u'/api/job/65/', u'/api/job/66/', u'/api/job/67/', u'/api/job/68/', u'/api/job/69/', u'/api/job/70/', u'/api/job/71/', u'/api/job/72/', u'/api/job/73/'], u'complete': True, u'created_at': u'2017-09-07T16:08:50.235897', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/17/', u'id': 17, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}

Job 67 Errored (Register testfs-OST0001):
{u'commands': [u'/api/command/17/'], u'write_locks': [{u'locked_item_content_type_id': 91, u'locked_item_id': 4, u'locked_item_uri': u'/api/target/4/', u'resource_uri': u''}], u'description': u'Register testfs-OST0001', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 4, u'locked_item_uri': u'/api/lnet_configuration/4/', u'resource_uri': u''}, {u'locked_item_content_type_id': 93, u'locked_item_id': 1, u'locked_item_uri': u'/api/target/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 92, u'locked_item_id': 2, u'locked_item_uri': u'/api/target/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 4, u'locked_item_uri': u'/api/lnet_configuration/4/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 4, u'locked_item_uri': u'/api/pacemaker_configuration/4/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 3, u'locked_item_uri': u'/api/lnet_configuration/3/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 3, u'locked_item_uri': u'/api/pacemaker_configuration/3/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 4, u'locked_item_uri': u'/api/lnet_configuration/4/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 4, u'locked_item_uri': u'/api/pacemaker_configuration/4/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 3, u'locked_item_uri': u'/api/lnet_configuration/3/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 3, u'locked_item_uri': u'/api/pacemaker_configuration/3/', u'resource_uri': u''}], u'class_name': u'RegisterTargetJob', u'step_results': {u'/api/step/118/': None}, u'created_at': u'2017-09-07T16:08:50.489113', u'modified_at': u'2017-09-07T16:08:50.489084', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/118/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/66/', u'/api/job/59/', u'/api/job/63/'], u'id': 67, u'resource_uri': u'/api/job/67/'}

Step 118 failed:
step_count: 2
console: modprobe osd_ldiskfs: 0


mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14 /mnt/testfs-OST0001: 108

mount.lustre: increased /sys/block/sdb/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: Cannot send after transport endpoint shutdown

mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14 /mnt/testfs-OST0001: 2

mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: No such file or directory
Is the MGS specification correct?
Is the filesystem name correct?
If upgrading, is the copied client log valid? (see upgrade docs)


description: RegisterTargetStep: {'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', 'primary_host': <ManagedHost: lotus-48vm18.lotus.hpdd.lab.intel.com>, 'mount_point': u'/mnt/testfs-OST0001', 'backfstype': 'ldiskfs', 'target': <ManagedTarget: testfs-OST0001>}
class_name: RegisterTargetStep
backtrace: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 305, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 282, in register_target

  File "/usr/lib/python2.7/site-packages/iml_common/filesystems/filesystem.py", line 89, in mount
    raise RuntimeError("Error (%s) mounting '%s': '%s' '%s'" % (result.rc, mount_point, result.stdout, result.stderr))

RuntimeError: Error (2) mounting '/mnt/testfs-OST0001': '' 'mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: No such file or directory
Is the MGS specification correct?
Is the filesystem name correct?
If upgrading, is the copied client log valid? (see upgrade docs)
'

created_at: 2017-09-07T16:09:35.624637
args: {u'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'primary_host': u'lotus-48vm18.lotus.hpdd.lab.intel.com', u'mount_point': u'/mnt/testfs-OST0001', u'backfstype': u'ldiskfs', u'target': u'testfs-OST0001'}
modified_at: 2017-09-07T16:10:38.907236
step_index: 0
state: failed
result: 
resource_uri: /api/step/118/
id: 118
log: 


--------------------- >> end captured stdout << ----------------------
```

But note that the failure is in the second `mount`:

```
mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14 /mnt/testfs-OST0001: 2

mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: No such file or directory
Is the MGS specification correct?
Is the filesystem name correct?
If upgrading, is the copied client log valid? (see upgrade docs)
```

not the first one:

```
mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14 /mnt/testfs-OST0001: 108

mount.lustre: increased /sys/block/sdb/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdb at /mnt/testfs-OST0001 failed: Cannot send after transport endpoint shutdown
```

That first mount failure is being [worked around](https://github.com/intel-hpdd/intel-manager-for-lustre/commit/51581cfd480f61df6dc3b8a6e8b49d24840ea6c8) already and is why the `mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14 /mnt/testfs-OST0001` is done twice.  But is not expected to fail the second time as it does here with an exit code of _2_.

It would be good to investigate this more deeply but the above run has suffered from the [chroma-diagnostics log truncation issue](https://github.com/intel-hpdd/intel-manager-for-lustre/issues/259).

**Comment by brianjmurrell** [comment]
Being tracked in the lustre project as [LU-9976|https://jira.hpdd.intel.com/browse/LU-9976].
