### ISSUE TITLE
mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13 /mnt/testfs-OST0001: 17

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#312]
Filed upstream as [LU-9577](https://jira.hpdd.intel.com/browse/LU-9577).

In a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1892/arch=x86_64,distro=el7), the following was observed:

```
test_creation_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 60, in test_creation_conf_params
    self._create_with_params()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 36, in _create_with_params
    'conf_params': {'llite.max_cached_mb': '16'}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 432, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/27/', u'/api/job/28/', u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/'], u'complete': True, u'created_at': u'2017-10-03T02:45:35.510024', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': 9, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/12/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/14/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/15/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/16/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/12/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/14/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/15/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/16/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
COMMAND 9: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/27/', u'/api/job/28/', u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/'], u'complete': True, u'created_at': u'2017-10-03T02:45:35.510024', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': 9, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}

Job 37 Errored (Register testfs-OST0001):
{u'commands': [u'/api/command/9/'], u'write_locks': [{u'locked_item_content_type_id': 88, u'locked_item_id': 4, u'locked_item_uri': u'/api/target/4/', u'resource_uri': u''}], u'description': u'Register testfs-OST0001', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 90, u'locked_item_id': 1, u'locked_item_uri': u'/api/target/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 89, u'locked_item_id': 2, u'locked_item_uri': u'/api/target/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 106, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 106, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}], u'class_name': u'RegisterTargetJob', u'step_results': {u'/api/step/76/': None}, u'created_at': u'2017-10-03T02:45:35.794745', u'modified_at': u'2017-10-03T02:45:35.794713', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/76/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/33/', u'/api/job/36/', u'/api/job/29/'], u'id': 37, u'resource_uri': u'/api/job/37/'}

Step 76 failed:
step_count: 2
console: modprobe osd_ldiskfs: 0


mount -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13 /mnt/testfs-OST0001: 17

mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0001 failed: File exists


description: RegisterTargetStep: {'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', 'primary_host': <ManagedHost: lotus-49vm15.lotus.hpdd.lab.intel.com>, 'mount_point': u'/mnt/testfs-OST0001', 'backfstype': 'ldiskfs', 'target': <ManagedTarget: testfs-OST0001>}
class_name: RegisterTargetStep
backtrace: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run
    result = self.manager._session._client.action_plugins.run(self.action, agent_daemon_context, self.args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 303, in run
    return fn(**args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 282, in register_target
    filesystem.mount(mount_point)

  File "/usr/lib/python2.7/site-packages/iml_common/filesystems/filesystem.py", line 89, in mount
    raise RuntimeError("Error (%s) mounting '%s': '%s' '%s'" % (result.rc, mount_point, result.stdout, result.stderr))

RuntimeError: Error (17) mounting '/mnt/testfs-OST0001': '' 'mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0001 failed: File exists
'

created_at: 2017-10-03T02:46:18.728628
args: {u'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'primary_host': u'lotus-49vm15.lotus.hpdd.lab.intel.com', u'mount_point': u'/mnt/testfs-OST0001', u'backfstype': u'ldiskfs', u'target': u'testfs-OST0001'}
modified_at: 2017-10-03T02:46:27.282740
step_index: 0
state: failed
result: 
resource_uri: /api/step/76/
id: 76
log: 


--------------------- >> end captured stdout << ----------------------
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1895)

**Comment by bradhoagland** [comment]
Fixed by LU-5020 which will be in the next Lustre LTS release (LU 2.10.2). 

The issue is unlikely to be seen in the field but can be worked-around with retry/reboot or addressed with one-off patch if necessary.

**Comment by brianjmurrell** [comment]
I will close this and we will just have to deal with support requests and failing tests if and as they happen.
