### ISSUE TITLE
Error: Error: rpmdb open failed

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#323]
Seeing this in SSI tests occasionally.

```
[06/Oct/2017:04:52:02] daemon INFO ActionRunner.fail 1866ec9c-42ae-46e0-9760-
ad1ec01bdc41: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run
    result = self.manager._session._client.action_plugins.run(self.action, agent_daemon_context, self.args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 303, in run
    return fn(**args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/agent_updates.py", line 103, in install_packages
    yum_util('clean')

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/yum_utils.py", line 74, in yum_util
    raise AgentShell.CommandExecutionError(result, cmd)   # Out of retries so raise for the caller..

CommandExecutionError: Error (1) running 'dnf clean all --enablerepo=*': '' 'error: rpmdb: BDB0113 Thread/process 24080/139819371984640 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
```

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1960

**Comment by brianjmurrell** [comment]
Yes, I have seen this also.  Wasn't sure how pervasive it was though.  There is a remedy:

```
# rm -f /var/lib/rpm/__db*
# rpm --rebuilddb
# yum clean all
# yum update
```

I suspect the last two are superfluous.

I guess we probably need to roll this into our code in the event of _yum_ failures.
