### ISSUE TITLE
((host is None) and (active_volume_node is None)) AssertionError

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#333]
In the [job_scheduler.log](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2016/arch=x86_64,distro=el7/artifact/test_logs/sosreport-lotus-43vm3-20171010211730/var/log/chroma/job_scheduler.log-20171011.gz) of [this test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2016/arch=x86_64,distro=el7) we can see:

```
[2017-10-10 22:05:10,219: INFO/job] create_parameters: host: 'lotus-43vm7.lotus.hpdd.lab.intel.com' active_volume_node: 'None'
[2017-10-10 22:05:10,292: ERROR/job_scheduler] Job 68: exception in get_steps: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 533, in _check_jobs
    job.steps = job.get_steps()
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1092, in get_steps
    True))]
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 897, in create_parameters
    ((host is None) and (active_volume_node is None))
AssertionError

[2017-10-10 22:05:10,292: INFO/job_scheduler] Job 68 completing (errored=False, cancelled=True)
```

This appears to have been the cause of the `create_filesystem()` failure in the _test_create_filesystem_with_failover_oss_chroma_controlled_ test in that run.

**Comment by brianjmurrell** [comment]
A different flavour of this issue can be seen in [this test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/2073):

```
test_creation_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 62, in test_creation_conf_params
    self.graceful_teardown(self.chroma_manager)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 750, in graceful_teardown
    timeout=LONG_TEST_TIMEOUT)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 358, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/53/', u'/api/job/54/', u'/api/job/55/', u'/api/job/56/', u'/api/job/57/', u'/api/job/58/', u'/api/job/59/', u'/api/job/60/', u'/api/job/61/'], u'complete': True, u'created_at': u'2017-10-13T17:57:07.234681', u'message': u'Remove file system testfs from configuration', u'cancelled': True, u'errored': False, u'resource_uri': u'/api/command/18/', u'id': 18, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
```

The [job_scheduler.log](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/2073/artifact/test_logs/sosreport-lotus-57vm13-20171014011941/var/log/chroma/job_scheduler.log) for this test run reports:

```
[2017-10-13 17:59:26,974: ERROR/job_scheduler] Job 61: exception in get_steps: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 533, in _check_jobs
    job.steps = job.get_steps()
  File "/usr/share/chroma-manager/chroma_core/models/filesystem.py", line 216, in get_steps
    'mgs_device_type': mgs_target.active_mount.volume_node.volume.storage_resource.to_resource_class().device_type(),
AttributeError: 'NoneType' object has no attribute 'to_resource_class'

[2017-10-13 17:59:26,974: INFO/job_scheduler] Job 61 completing (errored=False, cancelled=True)
```

**Comment by tanabarr** [comment]
in 5x SSI runs of #335  (2088,2090-2093) not seen any instances of #339 (#333) (meaning it probably resolves that failure)

**Comment by brianjmurrell** [comment]
This is still [being seen](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/2396) on master:

```
test_filesystem_stops_and_starts (tests.integration.shared_storage_configuration.test_stop_and_start_filesystem.TestStartingAndStoppingTargets) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_stop_and_start_filesystem.py", line 36, in test_filesystem_stops_and_starts
    self.set_state(filesystem['resource_uri'], fs_state)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 501, in set_state
    msg)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 485, in set_value
    command = self.wait_for_command(self.chroma_manager, command_id, verify_successful=(verify_successful != self.VERIFY_SUCCESS_NO), msg=msg, timeout=LONG_TEST_TIMEOUT)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 342, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/83/', u'/api/job/84/', u'/api/job/85/', u'/api/job/86/'], u'complete': True, u'created_at': u'2017-11-06T12:10:17.776047', u'message': u'Start file system testfs', u'cancelled': True, u'errored': False, u'resource_uri': u'/api/command/27/', u'id': 27, u'logs': u'\n'}
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 3, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 1, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 2, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 4, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk4', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 3, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 1, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 2, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 4, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 3, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 1, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 2, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 4, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 3, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 1, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 2, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 4, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 3, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 1, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 2, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 4, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk2', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 3, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 1, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 2, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 4, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk4', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 3, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 1, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 2, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 4, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 3, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 1, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 2, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 4, u'resource_uri': u'/api/volume_node/19/', u'id': 19, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 3, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 1, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 2, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 4, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 3, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-55vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 1, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-55vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 2, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-55vm6.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 4, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-55vm8.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk2', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
COMMAND 27: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/83/', u'/api/job/84/', u'/api/job/85/', u'/api/job/86/'], u'complete': True, u'created_at': u'2017-11-06T12:10:17.776047', u'message': u'Start file system testfs', u'cancelled': True, u'errored': False, u'resource_uri': u'/api/command/27/', u'id': 27, u'logs': u'\n'}


--------------------- >> end captured stdout << ----------------------
```

with:

```
[2017-11-06 12:10:17,989: ERROR/job_scheduler] Job 84: exception in get_steps: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 533, in _check_jobs
    job.steps = job.get_steps()
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1094, in get_steps
    True))]
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 899, in create_parameters
    ((host is None) and (active_volume_node is None))
AssertionError
```

in the job_scheduler.log, so I don't think #335 has (completely) fixed it. unfortunately.

**Comment by brianjmurrell** [comment]
I am still seeing this on master, FWIW.

**Comment by brianjmurrell** [comment]
We are now hitting this many times during a single test run even.
