### ISSUE TITLE
Need to restore the rsyslog model

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#359]
While running an instance of the upgrade test locally, the following failure happened:

```
test_access_all_data_all_endpoints (tests.integration.installation_and_upgrade.test_data_consistancy.TestAllEndPoints) ... /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Reading endpoint /api/alert_type/

Read endpoint /api/alert_type/

Reading endpoint /api/server_profile/

Read endpoint /api/server_profile/

Reading endpoint /api/power_control_type/

Read endpoint /api/power_control_type/

Reading endpoint /api/pacemaker_configuration/

Read endpoint /api/pacemaker_configuration/

Reading endpoint /api/copytool/

Read endpoint /api/copytool/

Reading endpoint /api/copytool_operation/

Read endpoint /api/copytool_operation/

Reading endpoint /api/client_mount/

Read endpoint /api/client_mount/

Reading endpoint /api/group/

Read endpoint /api/group/

Reading endpoint /api/log/

Read endpoint /api/log/

Reading endpoint /api/power_control_device/

Read endpoint /api/power_control_device/

Reading endpoint /api/network_interface/

Read endpoint /api/network_interface/

Reading endpoint /api/power_control_device_outlet/

Read endpoint /api/power_control_device_outlet/

Reading endpoint /api/nid/

Read endpoint /api/nid/

Reading endpoint /api/alert/

Read endpoint /api/alert/

Reading endpoint /api/job/
FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/installation_and_upgrade/test_data_consistancy.py", line 18, in test_access_all_data_all_endpoints
    self.get_json_by_uri(end_point['list_endpoint'], args={'limit': 0})
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 411, in get_json_by_uri
    return self.get_by_uri(uri, args, verify_successful).json
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 402, in get_by_uri
    self.assertEqual(response.status_code, 200, response.content)
AssertionError: {"error_message": "Sorry, this request could not be processed. Please try again later."}
```

Looking in the _http.log_ the following was seen at the time of the above failure:

```
[2017-10-24 01:25:01,279: ERROR/django.request.tastypie] Internal Server Error: /api/job/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 217, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 459, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 491, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1308, in get_list
    for obj in to_be_serialized[self._meta.collection_name]:
  File "/usr/share/chroma-manager/polymorphic/models.py", line 109, in __iter__
    yield item.downcast()
  File "/usr/share/chroma-manager/polymorphic/models.py", line 65, in downcast
    model = self.downcast_class
  File "/usr/share/chroma-manager/polymorphic/models.py", line 49, in downcast_class
    return ContentType.objects.get_for_id(self.content_type_id).model_class()
  File "/usr/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 101, in get_for_id
    self._add_to_cache(self.db, ct)
  File "/usr/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 116, in _add_to_cache
    key = (model._meta.app_label, model._meta.object_name.lower())
AttributeError: 'NoneType' object has no attribute '_meta'
```

**Comment by brianjmurrell** [comment]
Need to restore the rsyslog model.
