### ISSUE TITLE
EFS test failure due to corrupted pool

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#395]
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-existing-filesystem-configuration/2113/arch=x86_64,distro=el7//consoleFull
Jenkins build 2306

frequent agent deployment failures seen - file system detection failing repeatedly because agent is not deploying

Flock command fails with "repository listed more than once in the configuration" stderr and "package zfs is not installed" in stdout but then modprobe loads module successfully (zfs)

then we create the Pool on disk11 vm15 (mgt_index0 mounted as mdt)
then format target
then Mount
then add to fstab

then repeat for disk12 vm17 (mdt_index3 mounted as mdt3)
fails on mount

<details>
<summary>Expand for detail</summary>
<p>

```
2017-11-20 21:02:24,413 - test - DEBUG - remote_command[lotus-10vm15]: flock -x /var/lock/lustre_installer_lock -c 'rpm -q zfs || (cd /tmp && tar zxf lustre-zfs-el7-installer.tar.gz && cd lustre-zfs && ./install > /tmp/zfs_installer.stdout)'
2017-11-20 21:24:32,029 - test - INFO - lotus-10vm15: install blockdevice packages command flock -x /var/lock/lustre_installer_lock -c 'rpm -q zfs || (cd /tmp && tar zxf lustre-zfs-el7-installer.tar.gz && cd lustre-zfs && ./install > /tmp/zfs_installer.stdout)' exit_status 0
output:
 package zfs is not installed

stderr:
 Repository e2fsprogs is listed more than once in the configuration
Repository managerforlustre-manager-for-lustre is listed more than once in the configuration

2017-11-20 21:24:32,447 - test - DEBUG - remote_command[lotus-10vm15]: modprobe zfs
2017-11-20 21:24:34,263 - test - INFO - lotus-10vm15: install blockdevice packages command modprobe zfs exit_status 0
output:

stderr:

2017-11-20 21:24:34,264 - test - DEBUG - remote_command[lotus-10vm15]: systemctl disable zfs.target
2017-11-20 21:24:34,564 - test - INFO - prepare device command systemctl disable zfs.target exit_status 0
output:

stderr:

2017-11-20 21:24:34,564 - test - DEBUG - remote_command[lotus-10vm15]: zpool create zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11 -o cachefile=none -o multihost=on /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11
2017-11-20 21:24:35,615 - test - INFO - prepare device command zpool create zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11 -o cachefile=none -o multihost=on /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11 exit_status 0
output:

stderr:

2017-11-20 21:24:35,616 - test - DEBUG - remote_command[lotus-10vm15]: mkfs.lustre --backfstype=zfs --mdt --mgs  --index=0 --fsname=efs  zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/mgt_index0
2017-11-20 21:24:36,069 - test - INFO - mkfs.lustre output:

   Permanent disk data:
Target:     efs:MDT0000
Index:      0
Lustre FS:  efs
Mount type: zfs
Flags:      0x65
              (MDT MGS first_time update )
Persistent mount opts:
Parameters:
checking for existing Lustre data: not found
mkfs_cmd = zfs create -o canmount=off -o xattr=sa zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/mgt_index0
Writing zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/mgt_index0 properties
  lustre:version=1
  lustre:flags=101
  lustre:index=0
  lustre:fsname=efs
  lustre:svname=efs:MDT0000

2017-11-20 21:24:36,069 - test - DEBUG - remote_command[lotus-10vm15]: mkdir -p /mnt/mdt
2017-11-20 21:24:36,391 - test - DEBUG - remote_command[lotus-10vm15]: mount -t lustre zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/mgt_index0 /mnt/mdt
2017-11-20 21:24:37,174 - test - DEBUG - remote_command[lotus-10vm15]: echo 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11/mgt_index0   /mnt/mdt  lustre  defaults,_netdev    0 0' >> /etc/fstab
2017-11-20 21:24:37,383 - test - DEBUG - remote_command[lotus-10vm17]: flock -x /var/lock/lustre_installer_lock -c 'rpm -q zfs || (cd /tmp && tar zxf lustre-zfs-el7-installer.tar.gz && cd lustre-zfs && ./install > /tmp/zfs_installer.stdout)'
2017-11-20 21:39:27,541 - test - INFO - lotus-10vm17: install blockdevice packages command flock -x /var/lock/lustre_installer_lock -c 'rpm -q zfs || (cd /tmp && tar zxf lustre-zfs-el7-installer.tar.gz && cd lustre-zfs && ./install > /tmp/zfs_installer.stdout)' exit_status 0
output:
 package zfs is not installed

stderr:
 Repository e2fsprogs is listed more than once in the configuration
Repository managerforlustre-manager-for-lustre is listed more than once in the configuration

2017-11-20 21:39:27,541 - test - DEBUG - remote_command[lotus-10vm17]: modprobe zfs
2017-11-20 21:39:29,786 - test - INFO - lotus-10vm17: install blockdevice packages command modprobe zfs exit_status 0
output:

stderr:

2017-11-20 21:39:29,786 - test - DEBUG - remote_command[lotus-10vm17]: systemctl disable zfs.target
2017-11-20 21:39:30,429 - test - INFO - prepare device command systemctl disable zfs.target exit_status 0
output:

stderr:



2017-11-20 21:39:30,429 - test - DEBUG - remote_command[lotus-10vm17]: zpool create zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12 -o cachefile=none -o multihost=on /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12
2017-11-20 21:39:32,478 - test - INFO - prepare device command zpool create zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12 -o cachefile=none -o multihost=on /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12 exit_status 0
output:

stderr:

2017-11-20 21:39:32,478 - test - DEBUG - remote_command[lotus-10vm17]: mkfs.lustre --backfstype=zfs --mdt  --index=3 --fsname=efs --mgsnode=10.14.81.8@tcp0 zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12/mdt_index3
2017-11-20 21:39:38,693 - test - INFO - mkfs.lustre output:

   Permanent disk data:
Target:     efs:MDT0003
Index:      3
Lustre FS:  efs
Mount type: zfs
Flags:      0x61
              (MDT first_time update )
Persistent mount opts:
Parameters: mgsnode=10.14.81.8@tcp
checking for existing Lustre data: not found
mkfs_cmd = zfs create -o canmount=off -o xattr=sa zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12/mdt_index3
Writing zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12/mdt_index3 properties
  lustre:mgsnode=10.14.81.8@tcp
  lustre:version=1
  lustre:flags=97
  lustre:index=3
  lustre:fsname=efs
  lustre:svname=efs:MDT0003

2017-11-20 21:39:38,693 - test - DEBUG - remote_command[lotus-10vm17]: mkdir -p /mnt/mdt3
2017-11-20 21:39:38,899 - test - DEBUG - remote_command[lotus-10vm17]: mount -t lustre zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12/mdt_index3 /mnt/mdt3
2017-11-20 21:49:40,469 - test - ERROR - Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py", line 181, in create_lustre_filesystem_for_test
    ['--mdt'])
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py", line 318, in configure_target_device
    self.mount_target(block_device, target, filesystem.mount_path)
  File "/usr/share/chroma-manager/tests/integration/existing_filesystem_configuration/utils/create_lustre_filesystem.py", line 268, in mount_target
    'mount -t lustre %s %s' % (device, target['mount_path'])
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 121, in remote_command
    self.assertEqual(exit_status, expected_return_code, stderr)
AssertionError: mount.lustre: mount zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12/mdt_index3 at /mnt/mdt3 failed: Input/output error
Is the MGS running?
```
</p>
</details>

analysing job_scheduler and chroma_test logs show that agent is never deployed successfully (agent runs but fails to connect with manager)

agent logs and _zpool events_ command output indicate that pool is never imported or exported and no agent commands are issued on the pool

**Comment by brianjmurrell** [comment]
> frequent agent deployment failures seen - file system detection failing repeatedly because agent is not deploying

But just to be clear, surely these cannot be the cause of the corruption since a deployment failure would just be a (i.e. detection test failure) test failure after which whatever teardown/cleanup/setup for a new test would be performed, returning everything back to "fresh".

> Flock command fails

To be clear, the `flock` command itself is successful as we can see the `exit_status 0`.

> with "repository listed more than once in the configuration" stderr

That is a non-fatal warning so shouldn't cause anything else to fail/not happen.

> and "package zfs is not installed" in stdout but then modprobe loads module successfully (zfs)

**package zfs is not installed** is expected/handled with the `|| (cd ... )` after the `rpm -q zfs` so again, this is not a cause.

> then we create the Pool on disk11 vm15 (mgt_index0 mounted as mdt)

And the some time after that, it gets corrupted:

```
[ 2154.011564] WARNING: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11' has encountered an uncorrectable I/O failure and has been suspended.
```

> then repeat for disk12 vm17 (mdt_index3 mounted as mdt3)
> fails on mount

Because it too is corrupted:

```
[ 2485.475865] WARNING: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk12' has encountered an uncorrectable I/O failure and has been suspended.
```

So, two different devices corrupted around the same time.

> agent logs and zpool events command output indicate that pool is never imported or exported and no agent commands are issued on the pool

So this would indicate that it's the inter-test cleanup or the per-test filesystem setup that is corrupting disk(s).

**Comment by jgrund** [comment]
Pool failure occurrence:

```
Nov 20 2017 21:35:30.398015294 ereport.fs.zfs.io_failure
        class = "ereport.fs.zfs.io_failure"
        ena = 0x1f570b57fa100001
        detector = (embedded nvlist)
                version = 0x0
                scheme = "zfs"
                pool = 0x9658dcaa737664a4
        (end detector)
        pool = "zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11"
        pool_guid = 0x9658dcaa737664a4
        pool_state = 0x0
        pool_context = 0x0
        pool_failmode = "wait"
        time = 0x5a13bb22 0x17b93b3e 
        eid = 0x16
```
