### ISSUE TITLE
Kernel panic - not syncing: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1' has encountered an uncorrectable I/O failure and the failure mode property for this pool is set to panic.

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#402]
During a [test](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2623/arch=x86_64,distro=el7) the following failure was observed:

```
test_update_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 152, in test_update_conf_params
    self.graceful_teardown(self.chroma_manager)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 745, in graceful_teardown
    timeout=LONG_TEST_TIMEOUT)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 353, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 342, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/28/', u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/'], u'complete': True, u'created_at': u'2017-11-24T07:44:07.329606', u'message': u'Remove file system testfs from configuration', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/7/', u'id': 7, u'logs': u'\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
COMMAND 7: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/28/', u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/'], u'complete': True, u'created_at': u'2017-11-24T07:44:07.329606', u'message': u'Remove file system testfs from configuration', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/7/', u'id': 7, u'logs': u'\n\n\n\n\n'}

Job 31 Errored (Remove target testfs-OST0000 from the filesystem
*** WARNING *** this is destructive to your filesystem and irreversible):
{u'commands': [u'/api/command/7/'], u'write_locks': [{u'locked_item_content_type_id': 88, u'locked_item_id': 3, u'locked_item_uri': u'/api/target/3/', u'resource_uri': u''}], u'description': u'Remove target testfs-OST0000 from the filesystem\n*** WARNING *** this is destructive to your filesystem and irreversible', u'read_locks': [{u'locked_item_content_type_id': 106, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}], u'class_name': u'RemoveConfiguredTargetJob', u'step_results': {u'/api/step/68/': None}, u'created_at': u'2017-11-24T07:44:07.426399', u'modified_at': u'2017-11-24T07:44:07.426373', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/68/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/28/', u'/api/job/30/'], u'id': 31, u'resource_uri': u'/api/job/31/'}

Step 68 failed:
step_count: 2
console: 
description: Removing target testfs-OST0000 from pacemaker configuration
class_name: RemoveTargetFromPacemakerConfigStep
backtrace: Communications error with lotus-10vm5.lotus.hpdd.lab.intel.com because session terminated
created_at: 2017-11-24T07:44:33.270217
args: {u'host': u'lotus-10vm5.lotus.hpdd.lab.intel.com', u'target': u'testfs-OST0000', u'target_mount': u'lotus-10vm5.lotus.hpdd.lab.intel.com:primary:testfs-OST0000'}
modified_at: 2017-11-24T07:45:35.362391
step_index: 0
state: failed
result: 
resource_uri: /api/step/68/
id: 68
log: 

Job 33 Errored (Remove target testfs-MDT0000 from the filesystem
*** WARNING *** this is destructive to your filesystem and irreversible):
{u'commands': [u'/api/command/7/'], u'write_locks': [{u'locked_item_content_type_id': 89, u'locked_item_id': 2, u'locked_item_uri': u'/api/target/2/', u'resource_uri': u''}], u'description': u'Remove target testfs-MDT0000 from the filesystem\n*** WARNING *** this is destructive to your filesystem and irreversible', u'read_locks': [{u'locked_item_content_type_id': 106, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}], u'class_name': u'RemoveConfiguredTargetJob', u'step_results': {u'/api/step/69/': None}, u'created_at': u'2017-11-24T07:44:07.446110', u'modified_at': u'2017-11-24T07:44:07.446067', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/69/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/32/', u'/api/job/29/'], u'id': 33, u'resource_uri': u'/api/job/33/'}

Step 69 failed:
step_count: 2
console: 
description: Removing target testfs-MDT0000 from pacemaker configuration
class_name: RemoveTargetFromPacemakerConfigStep
backtrace: Could not contact server lotus-10vm5.lotus.hpdd.lab.intel.com no session after 30 seconds
created_at: 2017-11-24T07:45:35.455750
args: {u'host': u'lotus-10vm5.lotus.hpdd.lab.intel.com', u'target': u'testfs-MDT0000', u'target_mount': u'lotus-10vm5.lotus.hpdd.lab.intel.com:primary:testfs-MDT0000'}
modified_at: 2017-11-24T07:46:05.504376
step_index: 0
state: failed
result: 
resource_uri: /api/step/69/
id: 69
log: 


--------------------- >> end captured stdout << ----------------------
```

A look in the [messages file](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2666/arch=x86_64,distro=el7/artifact/test_logs/sosreport-lotus-10vm5-20171124184553/var/log/messages) for _lotus-10vm5_ during this test shows a spontaneous node reboot:

```
Nov 23 23:44:27 localhost stonith-ng[9633]:  notice: On loss of CCM Quorum: Ignore
Nov 23 23:44:32 localhost kernel: sdb: sdb1 sdb9
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Nov 23 23:48:53 localhost kernel: Initializing cgroup subsys cpuset
Nov 23 23:48:53 localhost kernel: Initializing cgroup subsys cpu
Nov 23 23:48:53 localhost kernel: Initializing cgroup subsys cpuacct
Nov 23 23:48:53 localhost kernel: Linux version 3.10.0-693.2.2.el7_lustre.x86_64 (jenkins@trevis-309-el7-x8664-1.trevis.hpdd.intel.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Tue Oct 3 03:51:53 UTC 2017
Nov 23 23:48:53 localhost kernel: Command line: BOOT_IMAGE=/vmlinuz-3.10.0-693.2.2.el7_lustre.x86_64 root=/dev/mapper/vg_00-lv_root ro crashkernel=auto rd.lvm.lv=vg_00/lv_root rd.lvm.lv=vg_00/lv_swap net.ifnames=0 console=tty0 LANG=en_US.UTF-8 console=ttyS0,115200
```

and a look in the console log for _lotus-10vm5_ at this time shows:

```
2017-11-23 23:44:09 [  918.803392] Lustre: Failing over testfs-OST0000
2017-11-23 23:44:09 [  918.814443] Lustre: server umount testfs-OST0000 complete
2017-11-23 23:44:21 [  930.550302]  sdb: sdb1 sdb9
2017-11-23 23:44:21 [  930.695614]  sdd: sdd1 sdd9
2017-11-23 23:44:39 [  949.266130] Kernel panic - not syncing: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1' has encountered an uncorrectable I/O failure and the failure mode property for this pool is set to panic.
2017-11-23 23:44:39 [  949.286289] CPU: 1 PID: 12951 Comm: mmp Tainted: P           OE  ------------   3.10.0-693.2.2.el7_lustre.x86_64 #1
2017-11-23 23:44:39 [  949.291593] Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
2017-11-23 23:44:39 [  949.295965]  ffff88007ab9e000 000000009d9985f7 ffff880043573d28 ffffffff816a3d8d
2017-11-23 23:44:39 [  949.300450]  ffff880043573da8 ffffffff8169dc74 ffff880000000010 ffff880043573db8
2017-11-23 23:44:39 [  949.304895]  ffff880043573d58 000000009d9985f7 ffff880043573dc0 ffff88007ab9e000
2017-11-23 23:44:39 [  949.309178] Call Trace:
2017-11-23 23:44:39 [  949.312420]  [<ffffffff816a3d8d>] dump_stack+0x19/0x1b
2017-11-23 23:44:39 [  949.316093]  [<ffffffff8169dc74>] panic+0xe8/0x20d
2017-11-23 23:44:39 [  949.319657]  [<ffffffffc0dbd546>] zio_suspend+0x106/0x110 [zfs]
2017-11-23 23:44:39 [  949.323416]  [<ffffffffc0d4414a>] mmp_thread+0x7ea/0x820 [zfs]
2017-11-23 23:44:39 [  949.327209]  [<ffffffffc0d437f0>] ? metaslab_check_free+0x190/0x190 [zfs]
2017-11-23 23:44:39 [  949.330833]  [<ffffffffc0d43960>] ? mmp_write_done+0x170/0x170 [zfs]
2017-11-23 23:44:39 [  949.334468]  [<ffffffffc0634fa1>] thread_generic_wrapper+0x71/0x80 [spl]
2017-11-23 23:44:39 [  949.337989]  [<ffffffffc0634f30>] ? __thread_exit+0x20/0x20 [spl]
2017-11-23 23:44:39 [  949.341182]  [<ffffffff810b098f>] kthread+0xcf/0xe0
2017-11-23 23:44:39 [  949.344170]  [<ffffffff810b08c0>] ? insert_kthread_work+0x40/0x40
2017-11-23 23:44:39 [  949.347320]  [<ffffffff816b4f18>] ret_from_fork+0x58/0x90
2017-11-23 23:44:39 [  949.350138]  [<ffffffff810b08c0>] ? insert_kthread_work+0x40/0x40
2017-11-23 23:44:39 [  949.354350] Kernel Offset: disabled

<ConMan> Console [lotus-10vm5] disconnected from <lotus-10:6004> at 11-23 23:48.
```

**Comment by jgrund** [comment]
Closing. Please re-open if seen on b4.1 on master afterwards.
