### ISSUE TITLE
chroma-config setup command results in unresponsive IML

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#404]
On an existing IML 4.0.0 installation, running `chroma-config setup` with or without further parameters, seems to complete successfully but then when trying to bring up the webpage for IML, nothing appears and eventually a `502 bad gateway` is returned.

This was experienced on lotus with Jenkins IML build 2353 but will probably occur on master given the build patch changes seem unrelated.

**Comment by jgrund** [comment]
Need more info on this one, this is a really core issue that we should see in testing.

Can you trace what is causing that 502?

**Comment by tanabarr** [comment]
this is when running the command after already having configured and set up IML, it sounds like this should only be run to initially set up IML and in that case , this is not a valid use case (and that should be made clear in documentation)

**Comment by jgrund** [comment]
Even then it shouldn't cause this issue. Can you reproduce / paste the resulting stacktrace behind the 502?

**Comment by tanabarr** [comment]
Here is the stack trace provided in the browser:
```
Exception rendering resources: Error: {"error_message": "Sorry, this request could not be processed. Please try again later."} From GET request to /api/filesystem/?limit=0
    at ResponseError (/usr/share/chroma-manager/ui-modules/node_modules/@iml/view-server/dist/bundle.js:4068:5)
    at ClientRequest.transport.request.r (/usr/share/chroma-manager/ui-modules/node_modules/@iml/view-server/dist/bundle.js:4085:42)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

**Comment by tanabarr** [comment]
`chroma-config validate` reports that services are all running (OK)

**Comment by tanabarr** [comment]
`chroma-config restart` results in GUI responding as normal

`chroma-config setup admin examplepassword localhost` results in the following exceptions for threads 1-4 in `/var/log/chroma/gunicorn-error.log`:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 299, in run
    connection.drain_events(timeout = 1)
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
    return connection.drain_events(**kwargs)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 320, in drain_events
    return amqp_method(channel, args)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 523, in _close
    self._x_close_ok()
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 551, in _x_close_ok
    self._send_method((10, 51))
  File "/usr/lib/python2.7/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 177, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 104] Connection reset by peer
```

Then , when refreshing the IML UI webpage (chrome browser), after a while of inactivity, `502: Bad Gateway` nginx message is displayed.

Surprisingly, `/var/log/nginx/error.log` is empty and presumably these messages are redirected somewhere else.
