### ISSUE TITLE
Upgrade issue from 3.1 to 4.0

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/intel-manager-for-lustre#418]
In the patch that added MMP support to ZFS (4.0), we added a new field to the kwargs that are passed in with `UpdateManagedTargetMount`. 

The class (and kwargs) are ultimately pickled and saved in the db as a text field under `chroma_core_step_result.args`.

This causes an issue after upgrading to 4.0 as when the (3.1) field is hydrated back to a dict it's missing the `primary` key and throws.

We need to figure out a way of either working around that field, or deriving it's value from 3.1 data.

#419  fixes this

**Comment by tanabarr** [comment]
relevant exception from manager http.log:
```
[2017-12-13 22:54:21,792: ERROR/django.request.tastypie] Internal Server Error: /api/step/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 217, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 459, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 491, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1310, in get_list
    bundles.append(self.full_dehydrate(bundle, for_list=True))
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 871, in full_dehydrate
    bundle.data[field_name] = method(bundle)
  File "/usr/share/chroma-manager/chroma_api/step.py", line 40, in dehydrate_description
    return bundle.obj.describe()
  File "/usr/share/chroma-manager/chroma_core/models/step_result.py", line 83, in describe
    return self.step_class.describe(self.args)
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1248, in describe
    return "Update %s managed target mount for target %s" % (cls._primary_text(kwargs), kwargs['target'])
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1244, in _primary_text
    return 'primary' if kwargs['primary'] is True else 'secondary'
KeyError: 'primary'
```
