### ISSUE TITLE
Can not display the first page 

### ISSUE THREAD

**Issue by xiaopang1001** [intel-hpdd/intel-manager-for-lustre#452]
### Description 

After installed V4.0.1.0, the first page showing following error:
Exception rendering resources: Error: <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    
  </body>
</html>
 From GET request to /api/session/
    at ResponseError (/usr/share/chroma-manager/ui-modules/node_modules/@iml/view-server/dist/bundle.js:4068:5)
    at ClientRequest.transport.request.r (/usr/share/chroma-manager/ui-modules/node_modules/@iml/view-server/dist/bundle.js:4085:42)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)

[debug]

server time: 2018-01-17T09:34:10.456Z

build: 4979

version: 4.0.1.0

is release: true

fqdn: iml

sysname: x86_64

nodename: iml

release: 3.10.0-514.26.2.el7.x86_64

version: Linux

machine: #1 SMP Tue Jul 4 15:04:05 UTC 2017

      

### Repro

What steps were taken leading to this issue

### Version

What version of IML?
V4.0.1.0
What Operating System?
CentOS
What Operating System version?
V7.3

**Comment by johnsonw** [comment]
Hello,

Can you please run 'iml-diagnostics' on the manager node and attach the compressed file to this ticket? Thanks.

Regards,

Will

**Comment by xiaopang1001** [comment]
[sosreport-iml001-20180119112721.tar.xz.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1645268/sosreport-iml001-20180119112721.tar.xz.zip)
Hi Johnsonw,
    Attached the file. Thanks for your great support.

Xiaopang

**Comment by johnsonw** [comment]
Hi Xiaopang,

It looks like there is an issue with your certs when looking at the gunicorn-error log:
```
2018-01-19 01:46:37 [11817] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 151, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 179, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 224, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/share/chroma-manager/urls.py", line 10, in <module>
    import chroma_api.urls
  File "/usr/share/chroma-manager/chroma_api/urls.py", line 39, in <module>
    import chroma_api.system_status
  File "/usr/share/chroma-manager/chroma_api/system_status.py", line 9, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
```
The description above sounds like a fresh install but when I looked at the install logs it looks like it was installed more than once:
```
WARNING: The installed version (4.0.2.0.4995.el7) did not change.
This is OK if the installer was intentionally re-run with the same version.
Otherwise, please contact support with details from /var/log/chroma/install.log.
```

I would try a fresh install of IML on a clean CentOS 7.4 box and see if you run into the same problem.

Regards,

Will

**Comment by xiaopang1001** [comment]
Hi Johnsonw
      You may not got the issue when doing a local fresh installation. The OS I used is some cloud virtual machine. Sounds there are some difference with the lcoal yum repos and the cloud yum repos.
     After i removed the following rpms :
 #rpm -e --nodeps python-gobject-base-3.22.0-1.el7.x86_64
 #rpm -e --nodeps python-linux-procfs-0.4.9-3.el7.noarch
 #rpm -e --nodeps python-py-1.4.32-1.el7.noarch
 #rpm -e --nodeps python-schedutils-0.4-6.el7.x86_64
And also when install python-urllib3-1.10.2-3.el7.noarch.rpm, I got some error so I copied it's contents from some other server.
After doing all these, IML works fine.

Thanks.
