### ISSUE TITLE
device-aggregator output empty after chroma-config restart command

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#492]
The `device-aggregator` output gets emptied after `chroma-config restart`.

This seems to be because nginx gets restarted and subsequent connection attempts from `scanner-proxy` are refused:
```
Mar 08 08:32:28 lotus-40vm15 node[3085]: Unable to generate HTTPS request connect ECONNREFUSED 10.14.82.102:443, Error: connect ECONNREFUSED 10.14.82.102:443
Mar 08 08:32:28 lotus-40vm15 node[3085]: at Object.exports._errnoException (util.js:1020:11)
Mar 08 08:32:28 lotus-40vm15 node[3085]: at exports._exceptionWithHostPort (util.js:1043:20)
Mar 08 08:32:28 lotus-40vm15 node[3085]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

Restarting the `scanner-proxy` on the storage servers repopulates the data.

**Comment by jgrund** [comment]
dup of https://github.com/intel-hpdd/device-scanner/issues/136
