### ISSUE TITLE
IML  displays not  all OST

### ISSUE THREAD

**Issue by Zubrania** [intel-hpdd/intel-manager-for-lustre#578]
### Description 

IML  displays not  all OST 

### Repro

Installation  of IML agent  to the host and filesystem detection

### Version

What version of IML 
4.0.4
What Operating System 
[root@lynx-iml ~]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

What Operating System version?

### iml-diagnostics

Attach any [`iml-diagnostics`](https://intel-hpdd.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) for nodes relevant to this issue.
[https://www.dropbox.com/s/u6cwa58vs7fvb62/sosreport-lynx-iml-20180506235832.tar.xz](https://www.dropbox.com/s/u6cwa58vs7fvb62/sosreport-lynx-iml-20180506235832.tar.xz)
the following  information  appears in log window  "No data for plugin linux from host ...."

**Comment by jgrund** [comment]
Hi @Zubrania 

Please attach an sos report for the node(s) where targets are not appearing.

It looks like one of your nodes is reporting 0 volumes, which seems like there was either an install issue or service failure on the agent.

You may want to try removing the server node via the IML GUI, and use 

```bash
yum autoremove chroma-agent
rm -rf /etc/yum.repos.d/Intel-Lustre-Agent.repo 
rm -rf /var/lib/chroma/ 
rm -rf /var/lib/iml/ 
```

to clear out all the monitor-mode packages. Then re-add the node again via the IML GUI.

**Comment by Zubrania** [comment]
Hi Joe

the attached sosreport  is  available here https://www.dropbox.com/s/8df5gw5wlovn891/sosreport-new-oss-06-20180507233837.tar.xz?dl=0 <https://www.dropbox.com/s/8df5gw5wlovn891/sosreport-new-oss-06-20180507233837.tar.xz?dl=0>


What I can see  in chroma-agent.log 

[08/May/2018:00:03:15] daemon ERROR Error (1) running 'zpool import -N -o readonly=on -o cachefile=none zostpool10': '' 'cannot import 'zostpool10': pool is imported on new-oss-05 (hostid: 0x65ca7714)
Export the pool on the other system, then run 'zpool import'.
'
[08/May/2018:00:03:15] daemon ERROR ZfsPool unavailable and could not be retrieved from store: u'1688035456817628545' (pool info: {u'status': u'The pool is currently imported by another system.', u'see': u'http://zfsonlinux.org/msg/ZFS-8000-EY', u'devices': {}, u'state': u'UNAVAIL', u'action': u'The pool must be exported from new-oss-05 (hostid=65ca7714)\n\tbefore it can be safely imported.', u'id': u'1688035456817628545', u'pool': u'zostpool10'})
[08/May/2018:00:03:19] daemon ERROR Error (1) running 'zpool import -N -o readonly=on -o cachefile=none zostpool08': '' 'cannot import 'zostpool08': pool is imported on new-oss-05 (hostid: 0x65ca7714)
Export the pool on the other system, then run 'zpool import'.
'
[08/May/2018:00:03:19] daemon ERROR ZfsPool unavailable and could not be retrieved from store: u'16697103411979478295' (pool info: {u'status': u'The pool is currently imported by another system.', u'see': u'http://zfsonlinux.org/msg/ZFS-8000-EY', u'devices': {}, u'state': u'UNAVAIL', u'action': u'The pool must be exported from new-oss-05 (hostid=65ca7714)\n\tbefore it can be safely imported.', u'id': u'16697103411979478295', u'pool': u'zostpool08'})
[08/May/2018:00:03:22] daemon ERROR Error in plugin linux: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 449, in poll
    data = session.poll()

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 230, in poll
    return self._plugin.start_session()

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/linux.py", line 98, in start_session
    return self._scan_devices(True)

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/linux.py", line 81, in _scan_devices
    full_scan_result = self._full_scan()

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/linux.py", line 60, in _full_scan
    local_fs = LocalFilesystems(block_devices).all()

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/linux_components/local_filesystems.py", line 11, in __init__
    fstab = Fstab()

  File "/usr/lib/python2.7/site-packages/chroma_agent/utils.py", line 46, in __init__
    device = AgentShell.try_run(['blkid', '-U', uuid]).strip()

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/shell.py", line 106, in try_run
    raise AgentShell.CommandExecutionError(result, arg_list)

CommandExecutionError: Error (2) running 'blkid -U 1cd50efb-e76b-47ee-b95f-360f8ce9825a': '' ‘'


zostpool08 and zostpool10  are  running  by default  on  new-oss-05 node
zostpool09 and zostpool11  are  running  by default  on  new-oss-06 node

nodes new-oss-05 new-oss-06  create cluster

[root@new-oss-06 ~]# pcs status
Cluster name: OSS05-OSS06
Stack: corosync
Current DC: new-oss-05 (version 1.1.16-12.el7_4.8-94ff4df) - partition with quorum
Last updated: Tue May  8 00:11:51 2018
Last change: Mon May  7 23:23:14 2018 by root via cibadmin on new-oss-06

2 nodes configured
12 resources configured

Online: [ new-oss-05 new-oss-06 ]

Full list of resources:

 Resource Group: group_ost08
     lustre_zostpool08  (ocf::pacemaker:ZFS):   Started new-oss-05
     lustre_ost08       (ocf::lustre:Lustre):   Started new-oss-05
 Resource Group: group_ost09
     lustre_zostpool09  (ocf::pacemaker:ZFS):   Started new-oss-06
     lustre_ost09       (ocf::lustre:Lustre):   Started new-oss-06
 Resource Group: group_ost10
     lustre_zostpool10  (ocf::pacemaker:ZFS):   Started new-oss-05
     lustre_ost10       (ocf::lustre:Lustre):   Started new-oss-05
 Resource Group: group_ost11
     lustre_zostpool11  (ocf::pacemaker:ZFS):   Started new-oss-06
     lustre_ost11       (ocf::lustre:Lustre):   Started new-oss-06
 ipmi-new-oss-05        (stonith:fence_ipmilan):        Started new-oss-05
 ipmi-new-oss-06        (stonith:fence_ipmilan):        Started new-oss-06
 Clone Set: healthLNET-clone [healthLNET]
     Started: [ new-oss-05 new-oss-06 ]

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
[root@new-oss-06 ~]#

**Comment by jgrund** [comment]
@Zubrania that last sos report link is 404ing, can you reupload?

**Comment by Zubrania** [comment]
@Joe

PLease find the sosreport under the following  link
https://www.dropbox.com/s/gfwjlio2kciwkwu/sosreport-new-oss-06-20180507233837.tar.xz?dl=0 <https://www.dropbox.com/s/gfwjlio2kciwkwu/sosreport-new-oss-06-20180507233837.tar.xz?dl=0>

**Comment by jgrund** [comment]
It is blowing up trying to find:  `1cd50efb-e76b-47ee-b95f-360f8ce9825a`. Tracking down where that's coming from.

**Comment by Zubrania** [comment]
@Joe

Thank you for pointing me on a  root cause.

**Comment by jgrund** [comment]
@Zubrania no problem. Let me know if you can see volumes once that issue is fixed.

**Comment by Zubrania** [comment]
@Joe 
It already  fixed  and I can  see all OSTs

**Comment by jgrund** [comment]
Great, I'll close this then.
