### ISSUE TITLE
Second round of manual testing for IML@4.0.6.0

### ISSUE THREAD

**Issue by johnsonw** [intel-hpdd/intel-manager-for-lustre#629]
**Mixed managed LDISKFS and ZFS:**
I was able to add servers without any problem, update lnet, power control, and setup both OSS's with ZFS volumes. When I attempted to create the filesystem there was a timeout on the MDS:

![image](https://user-images.githubusercontent.com/1100657/40424437-9b849274-5e63-11e8-8e67-3f2ce694545f.png)

![image](https://user-images.githubusercontent.com/1100657/40424446-9ee9b228-5e63-11e8-9cdc-f5f50d477dd2.png)

```
modprobe osd_ldiskfs: 0


mount -t lustre /dev/disk/by-id/ata-VBOX_HARDDISK_MDT00000000000000000 /mnt/fs-MDT0000: 110

mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/fs-MDT0000 failed: Connection timed out

------------------
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run
    result = self.manager._session._client.action_plugins.run(self.action, agent_daemon_context, self.args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 303, in run
    return fn(**args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 298, in register_target
    filesystem.mount(mount_point)

  File "/usr/lib/python2.7/site-packages/iml_common/filesystems/filesystem.py", line 91, in mount
    raise RuntimeError("Error (%s) mounting '%s': '%s' '%s'" % (result.rc, mount_point, result.stdout, result.stderr))

RuntimeError: Error (110) mounting '/mnt/fs-MDT0000': '' 'mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/fs-MDT0000 failed: Connection timed out
'
```

Logs are attached here:
[mixed-managed-logs.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/2030996/mixed-managed-logs.zip)

**Comment by johnsonw** [comment]
Second round of testing:

**OS Details**:
```
[root@adm ~]# uname -r
3.10.0-862.2.3.el7.x86_64
[root@adm ~]# cat /etc/*elease
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
```

**Lustre details**:
```
[root@mds1 ~]# yum list installed | grep lustre
dnf.noarch                            1.1.5-2.01.el7.centos           @managerforlustre-manager-for-lustre
dnf-conf.noarch                       1.1.5-2.01.el7.centos           @managerforlustre-manager-for-lustre
fence-agents-vbox.x86_64              4.0.24-3.el7.centos             @managerforlustre-manager-for-lustre
iml-device-scanner.noarch             1.1.1-1.el7.centos              @managerforlustre-manager-for-lustre
iml_sos_plugin.noarch                 2.1.0-1.el7.centos              @managerforlustre-manager-for-lustre
kernel.x86_64                         3.10.0-862.2.3.el7_lustre       installed
kernel-debuginfo-common-x86_64.x86_64 3.10.0-862.2.3.el7_lustre       installed
kernel-devel.x86_64                   3.10.0-862.2.3.el7_lustre       installed
kmod-lustre.x86_64                    2.10.4-1.el7                    installed
kmod-lustre-osd-ldiskfs.x86_64        2.10.4-1.el7                    installed
lustre.x86_64                         2.10.4-1.el7                    installed
lustre-all-dkms.noarch                2.10.4-1.el7                    installed
lustre-ldiskfs-zfs.x86_64             1-3.el7.centos                  installed
lustre-osd-ldiskfs-mount.x86_64       2.10.4-1.el7                    installed
lustre-osd-zfs-mount.x86_64           2.10.4-1.el7                    installed
```

**Lustre Client details**:
```
[root@c1 ~]# yum list installed | grep lustre
kmod-lustre-client.x86_64            2.10.4-1.el7                   @downloads.hpdd.intel.com_public_lustre_lustre-2.10.4_el7_client_
lustre-client.x86_64                 2.10.4-1.el7                   @downloads.hpdd.intel.com_public_lustre_lustre-2.10.4_el7_client_
```

**Power Control**:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/1100657/40436440-f7b8b94a-5e80-11e8-9928-05e4771653b0.png">

**Volumes Page**:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1100657/40436594-474e127a-5e81-11e8-8c0b-3ab3e9ee2210.png">

**All servers setup properly for lnet**:
mds1:
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1100657/40436621-5d92d7c8-5e81-11e8-92cf-f5d45140ae8b.png">
mds2:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/1100657/40436656-73efa294-5e81-11e8-9bd6-f46eb84f7371.png">
oss1:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1100657/40436674-805f1d52-5e81-11e8-9d4b-0ddb8a8494bd.png">
oss2:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/1100657/40436698-8f98a73e-5e81-11e8-9751-2bbb7242d7c9.png">

**Creating Filesystem**:
![image](https://user-images.githubusercontent.com/1100657/40436942-157fec54-5e82-11e8-9fe4-e6280d173562.png)

**Filesystem created successfully**:
![image](https://user-images.githubusercontent.com/1100657/40437126-8512942c-5e82-11e8-840e-7582bb4e242c.png)

![image](https://user-images.githubusercontent.com/1100657/40437158-984fa4d0-5e82-11e8-94d0-8e179c271199.png)

**Charts**:
![image](https://user-images.githubusercontent.com/1100657/40437256-da49dbc6-5e82-11e8-8634-5b8ae7d7a953.png)

**Failover (Stopping oss1)**:
![image](https://user-images.githubusercontent.com/1100657/40437395-3d278e64-5e83-11e8-8edf-63128418bacf.png)

![image](https://user-images.githubusercontent.com/1100657/40437411-4947b606-5e83-11e8-8f0f-08a43e14c3d7.png)

**Failback (Starting oss1)**:
![image](https://user-images.githubusercontent.com/1100657/40437593-bd8647bc-5e83-11e8-87de-01ab593148d7.png)

![image](https://user-images.githubusercontent.com/1100657/40437659-f09db7c0-5e83-11e8-8c1c-fc087e0ddc4e.png)

![image](https://user-images.githubusercontent.com/1100657/40437679-fdddf724-5e83-11e8-8a9f-c8d573615777.png)

**Results**:
This test was successful. The last test I did was with a different binary so it's possible there was something different.

Log Files: 
[server-logs.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/2031970/server-logs.zip)
