### ISSUE TITLE
SSI: intermittent failure get_shared_volumes not reporting any ha

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#633]
`get_shared_volumes` is reporting no available HA volumes, smells like something happening with aggregator or scanner services stopping.

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/5680
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/5675
```
test_creation_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 60, in test_creation_conf_params
    self._create_with_params()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 17, in _create_with_params
    volumes = self.wait_for_shared_volumes(4, 2)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 464, in wait_for_shared_volumes
    self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 147, in wait_until_true
    'Timed out waiting for %s\nError Message %s' % (inspect.getsource(lambda_expression), error_message))
AssertionError: Timed out waiting for         self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)

Error Message 
```

regarding volumes and volume nodes reported:

```
test: INFO: Found these HA volumes: '[]'
test: DEBUG:         self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)
 evaluated to False
```

**Comment by jgrund** [comment]
Dup of: 

https://github.com/intel-hpdd/intel-manager-for-lustre/issues/614

The issue is that occasionally two servers doing mcast port selection will select each other's ports.
