### ISSUE TITLE
 IEEL 2.4.2.7 to Lustre 2.10.1 LTS & IML 4.0.6-- Database Migration Issue

### ISSUE THREAD

**Issue by yguvvala** [intel-hpdd/intel-manager-for-lustre#637]
### Description 

We are following https://github.com/intel-hpdd/intel-manager-for-lustre/issues/152 to upgrade from IEEL 2.4.2.7 to Lustre 2.10.1LTS & IML 4.0.6 but ran into this issue while migrating database. 

### Repro

Followed steps to upgrade IML only sofar

### Version

What version of IML? 
What Operating System? Cent OS 
What Operating System version? 7.4

### iml-diagnostics

[root@iml chroma]# chroma-config setup -v
Starting setup...

DB already accessible
Creating database tables...
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for tastypie:
- Nothing to migrate.
 - Loading initial data for tastypie.
Installed 0 object(s) from 0 fixture(s)
Running migrations for chroma_core:
 - Migrating forwards to 0039_add_primary_umtm_stepresults.
 > chroma_core:0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake
FATAL ERROR - The following SQL query failed: insert into chroma_core_corosyncconfiguration (state_modified_at, state, immutable_state, content_type_id, host_id) values ('2018-05-30 16:03:37.755588', 'started', 'f', 161, 9)
The error was: null value in column "corosync_reported_up" violates not-null constraint
DETAIL:  Failing row contains (1, 2018-05-30 16:03:37.755588+00, started, f, null, 161, 9, null, null).

Error in migration: chroma_core:0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake
Traceback (most recent call last):
  File "/usr/bin/chroma-config", line 10, in <module>
    load_entry_point('chroma-manager==4.0.6.0', 'console_scripts', 'chroma-config')()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 878, in chroma_config
    errors = service_config.setup(username, password, ntpserver, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 593, in setup
    error = self._setup_database(username, password, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 563, in _setup_database
    self._syncdb()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 545, in _syncdb
    ManagementUtility(args).execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/usr/share/chroma-manager/chroma_core/migrations/0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake.py", line 258, in forwards
    create_action_record(model_name, state, host_id)
  File "/usr/share/chroma-manager/chroma_core/migrations/0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake.py", line 242, in create_action_record
    "values ('%s', '%s', 'f', %s, %s)" % (model_name, datetime.datetime.now(), state, ct.id, host_id))
  File "/usr/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
django.db.utils.IntegrityError: null value in column "corosync_reported_up" violates not-null constraint
DETAIL:  Failing row contains (1, 2018-05-30 16:03:37.755588+00, started, f, null, 161, 9, null, null).

Attach any [`iml-diagnostics`](https://intel-hpdd.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) for nodes relevant to this issue.

**Comment by jgrund** [comment]
Hi @yguvvala,

Just a note, you can find official upgrade docs at https://intel-hpdd.github.io/Online-Help/docs/Upgrade_Guide/Upgrade_EE-2.4-el6_to_LU-LTS-el7.html

Can you please use either `chroma-diagnostics` or [`iml-diagnostics`](https://intel-hpdd.github.io/Online-Help/docs/Install_Guide/ig_ch_16_appD_getting_help.html#run-iml-diagnostics) to share the current state of your database on the manager node?

**Comment by johnsonw** [comment]
Hi @yguvvala,

I don't see the database attached to the sos report. Can you please export the database using the following command?

```
# Switch to the postgres user
su - postgres -c "pg_dump -U chroma -F p -w -T 'chroma_core_series*' -T 'chroma_core_sample*' -T 'chroma_core_logmessage*' -f /tmp/chromadb_backup_06_05_2018.sql"
```

Also, if you are able to load the IML page, can you please scroll down to the bottom and copy the footer and then paste it into this ticket? Thanks.

Regards,

Will

**Comment by johnsonw** [comment]
As mentioned in the chat, I still need to understand why importing your database into a new install of IML@2.4.1.0 has an issue. That being said, I have a patch that should help you get passed the migration issue. 

Please upload [dell-469.tar.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/2074774/dell-469.tar.zip) to your manager node when you are ready to run `chroma-config setup -v`. Unzip the file, cd into `dell-469` and run "./setup.sh". 

This will copy the updated migration files to the appropriate directory. After running the script, run `chroma-config setup -v` and the migration should complete successfully. Please keep me updated.

Regards,

Will

**Comment by uberlinuxguy** [comment]
I ran the patch on @yguvvala 's behalf this morning.  we got quite a bit further but still errored out...

`[root@iml dell-469]# chroma-config setup -v
Starting setup...

DB already accessible
Creating database tables...
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for tastypie:
- Nothing to migrate.
 - Loading initial data for tastypie.
Installed 0 object(s) from 0 fixture(s)
Running migrations for chroma_core:
 - Migrating forwards to 0039_add_primary_umtm_stepresults.
 > chroma_core:0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake
 > chroma_core:0024_auto__del_event__add_commandalert__add_getlnetstatejob__del_field_aler
 > chroma_core:0025_auto__add_field_serverprofile_rsyslog__add_field_serverprofile_ntp__ad
 > chroma_core:0026_auto__add_unconfigurecorosync2job__add_startcorosync2job__add_configur
 > chroma_core:0027_auto__del_setupworkertjob__del_removehostjob__add_setupworkerjob__add_
 > chroma_core:0028_auto__add_field_alertevent__message__add_field_ipmibmcunavailablealert
 > chroma_core:0029_auto__add_triggerpluginupdatesjob
 > chroma_core:0030_auto__add_field_volume_usable_for_lustre
 > chroma_core:0031_auto__add_stonithnotenabledalert
 > chroma_core:0032_remove_unused_tables
 > chroma_core:0033_health_status_procedure
 > chroma_core:0034_api_key_procedure
 > chroma_core:0035_auto__del_userprofile
 > chroma_core:0036_auto__del_unconfigurersyslogjob__del_rsyslogconfiguration__del_configu
 > chroma_core:0037_remove_rsyslog_types
 > chroma_core:0038_del_command_dismissed
 > chroma_core:0039_add_primary_umtm_stepresults
 - Loading initial data for chroma_core.
Installed 0 object(s) from 0 fixture(s)
Loaded 13 default power device types.

Synced:
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > south

Migrated:
 - tastypie
 - chroma_core
User accounts already created
API user created
NTP Server [localhost]: 
Writing ntp configuration: localhost 
Restarting ntp
Starting RabbitMQ...
Creating RabbitMQ user...
Creating RabbitMQ vhost...
Enabling daemons
Starting daemons
Some services failed to start: corosync, http_agent, job_scheduler, lustre_audit, plugin_runner, power_control, stats, syslog
Traceback (most recent call last):
  File "/usr/bin/chroma-config", line 10, in <module>
    load_entry_point('chroma-manager==4.0.6.0', 'console_scripts', 'chroma-config')()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 878, in chroma_config
    errors = service_config.setup(username, password, ntpserver, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 601, in setup
    self._start_services()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 333, in _start_services
    raise RuntimeError(msg)
RuntimeError: Some services failed to start: corosync, http_agent, job_scheduler, lustre_audit, plugin_runner, power_control, stats, syslog
[root@iml dell-469]# systemctl status corosync
Unit corosync.service could not be found.
[root@iml dell-469]# systemctl status http_agent
Unit http_agent.service could not be found.
[root@iml dell-469]# systemctl status syslog
Unit syslog.service could not be found.
`

**Comment by johnsonw** [comment]
Great to hear! Thanks again for your patience. Please let me know when the upgrade is complete or if you run into any further issues. 

Please note the following:
1. PR to fix this issue: https://github.com/intel-hpdd/intel-manager-for-lustre/pull/647
2. Issue to update upgrade instructions to indicate that patchless kernels are not supported: https://github.com/intel-hpdd/Online-Help/issues/89

**Comment by johnsonw** [comment]
Good morning. I wanted to check in and see if this issue is now resolved?

Regards,

Will

**Comment by johnsonw** [comment]
Please see the attached script to help resolve the volumes on the volumes page.

[fix-db.py.zip](https://github.com/intel-hpdd/intel-manager-for-lustre/files/2098143/fix-db.py.zip)
