### ISSUE TITLE
get_shared_volumes() doesn't return the necessary number of available volumes

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#81]
intermittent test failure not related to zfs devices

```Timed out waiting for         self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)```

get_shared_volumes doesn't return the necessary number of available volumes
this could be to do with deficiencies in the device scanning.

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/376/arch=x86_64,distro=el7//consoleFull

```======================================================================
FAIL: test_create_filesystem_with_failover_mgs (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 44, in test_create_filesystem_with_failover_mgs
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 14, in _test_create_filesystem_with_failover
    filesystem_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 348, in create_filesystem_standard
    ha_volumes = self.wait_for_shared_volumes(4, 4)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 487, in wait_for_shared_volumes
    self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 140, in wait_until_true
    'Timed out waiting for %s\nError Message %s' % (inspect.getsource(lambda_expression), error_message))
AssertionError: Timed out waiting for         self.wait_until_true(lambda: len(self.get_shared_volumes(required_hosts)) >= expected_volumes)
Error Message 
```

**Comment by tanabarr** [comment]
other occurrence: http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/380/arch=x86_64,distro=el7//consoleFull
