### ISSUE TITLE
check_stats() failing to report metric names

### ISSUE THREAD

**Issue by tanabarr** [intel-hpdd/intel-manager-for-lustre#83]
metric names not being returned from the API for an OST, we need to be sure whether this is an API (possibly long polling) issue or Lustre is not making the stats available.

http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/372/arch=x86_64,distro=el7//consoleFull

```test_create_filesystem_with_failover_mgs (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 44, in test_create_filesystem_with_failover_mgs
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 36, in _test_create_filesystem_with_failover
    self.check_stats(filesystem_id)
  File "/usr/share/chroma-manager/tests/integration/core/stats_testcase_mixin.py", line 158, in check_stats
    'Error in verifying expected MDT metric names being returned from API')
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 140, in wait_until_true
    'Timed out waiting for %s\nError Message %s' % (inspect.getsource(lambda_expression), error_message))
AssertionError: Timed out waiting for         self.wait_until_true(lambda: self._compare_target_metric_names('OST', self.ost_stats, filesystem_id),
                             'Error in verifying expected MDT metric names being returned from API')
Error Message Error in verifying expected MDT metric names being returned from API
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/515):

```
test_create_filesystem_with_failover_mds (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 72, in test_create_filesystem_with_failover_mds
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 36, in _test_create_filesystem_with_failover
    self.check_stats(filesystem_id)
  File "/usr/share/chroma-manager/tests/integration/core/stats_testcase_mixin.py", line 158, in check_stats
    'Error in verifying expected MDT metric names being returned from API')
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 140, in wait_until_true
    'Timed out waiting for %s\nError Message %s' % (inspect.getsource(lambda_expression), error_message))
AssertionError: Timed out waiting for         self.wait_until_true(lambda: self._compare_target_metric_names('OST', self.ost_stats, filesystem_id),
                             'Error in verifying expected MDT metric names being returned from API')

Error Message Error in verifying expected MDT metric names being returned from API
```

**Comment by tanabarr** [comment]
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/897/arch=x86_64,distro=el7//consoleFull is another occurrence

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/906/arch=x86_64,distro=el7):

```
test_create_filesystem_with_failover_oss_chroma_controlled (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 134, in test_create_filesystem_with_failover_oss_chroma_controlled
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 37, in _test_create_filesystem_with_failover
    self.check_stats(filesystem_id)
  File "/usr/share/chroma-manager/tests/integration/core/stats_testcase_mixin.py", line 158, in check_stats
    'Error in verifying expected MDT metric names being returned from API')
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 140, in wait_until_true
    'Timed out waiting for %s\nError Message %s' % (inspect.getsource(lambda_expression), error_message))
AssertionError: Timed out waiting for         self.wait_until_true(lambda: self._compare_target_metric_names('OST', self.ost_stats, filesystem_id),
                             'Error in verifying expected MDT metric names being returned from API')

Error Message Error in verifying expected MDT metric names being returned from API
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 3, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 4, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 2, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 3, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 4, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 2, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk4', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 3, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 4, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 2, u'resource_uri': u'/api/volume_node/21/', u'id': 21, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 3, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 4, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 2, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 3, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 4, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 2, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk2', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/47/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 1, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 3, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 1, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 4, u'resource_uri': u'/api/volume_node/13/', u'id': 13, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'host_id': 2, u'resource_uri': u'/api/volume_node/18/', u'id': 18, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk5', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/26/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 1, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 3, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 2, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 4, u'resource_uri': u'/api/volume_node/12/', u'id': 12, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk4', u'host_id': 2, u'resource_uri': u'/api/volume_node/17/', u'id': 17, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk4', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/49/', u'volume_nodes': [{u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 1, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 3, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 4, u'resource_uri': u'/api/volume_node/14/', u'id': 14, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'host_id': 2, u'resource_uri': u'/api/volume_node/21/', u'id': 21, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk3', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'ZfsPool', u'storage_resource': u'/api/storage_resource/51/', u'volume_nodes': [{u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 1, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/3/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 3, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/4/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 4, u'resource_uri': u'/api/volume_node/15/', u'id': 15, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 4, u'primary': False, u'host': u'/api/host/2/', u'path': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'host_id': 2, u'resource_uri': u'/api/volume_node/20/', u'id': 20, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10672993730'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/24/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 1, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-9vm5.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/3/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 3, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-9vm7.lotus.hpdd.lab.intel.com'}, {u'use': False, u'volume_id': 5, u'primary': False, u'host': u'/api/host/4/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 4, u'resource_uri': u'/api/volume_node/11/', u'id': 11, u'host_label': u'lotus-9vm8.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk2', u'host_id': 2, u'resource_uri': u'/api/volume_node/16/', u'id': 16, u'host_label': u'lotus-9vm6.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk2', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}

--------------------- >> end captured stdout << ----------------------
```
