### ISSUE TITLE
Communications error with test001.localdomain because session terminated in register_simulated_hosts on simulator ssi

### ISSUE THREAD

**Issue by brianjmurrell** [intel-hpdd/intel-manager-for-lustre#92]
In http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration-with-simulator/distro=el7,type=master/350/:
```
test_create_ost (tests.integration.shared_storage_configuration.test_targets.TestTargets) ... FAIL
FAIL
Traceback (most recent call last):
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/shared_storage_configuration/test_targets.py", line 36, in test_create_ost
    filesystem_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 339, in create_filesystem_standard
    hosts = self.add_hosts(host_addresses)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 265, in _add_hosts
    self.register_simulated_hosts(addresses)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 260, in register_simulated_hosts
    self.wait_for_commands(self.chroma_manager, host_create_command_ids.values())
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/home/chromatest/chroma_test_env/intel-manager-for-lustre/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/3068/', u'/api/job/3069/', u'/api/job/3070/', u'/api/job/3071/', u'/api/job/3072/', u'/api/job/3073/', u'/api/job/3074/', u'/api/job/3075/', u'/api/job/3076/', u'/api/job/3077/', u'/api/job/3078/'], u'complete': True, u'created_at': u'2017-06-14T20:46:06.116804+00:00', u'message': u'Deploying agent to host test001', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/795/', u'id': u'795', u'logs': u''}
-------------------- >> begin captured stdout << ---------------------
COMMAND 795: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/3068/', u'/api/job/3069/', u'/api/job/3070/', u'/api/job/3071/', u'/api/job/3072/', u'/api/job/3073/', u'/api/job/3074/', u'/api/job/3075/', u'/api/job/3076/', u'/api/job/3077/', u'/api/job/3078/'], u'complete': True, u'created_at': u'2017-06-14T20:46:06.116804+00:00', u'message': u'Deploying agent to host test001', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/795/', u'id': u'795', u'logs': u''}

Job 3068 Errored (Install packages on server test001):
{u'commands': [u'/api/command/795/'], u'write_locks': [{u'locked_item_content_type_id': 65, u'locked_item_id': 160, u'locked_item_uri': u'/api/host/160/', u'resource_uri': u''}], u'description': u'Install packages on server test001', u'read_locks': [], u'class_name': u'InstallHostPackagesJob', u'step_results': {u'/api/step/5273/': None}, u'created_at': u'2017-06-14T20:46:06.483010+00:00', u'modified_at': u'2017-06-14T20:46:06.482980+00:00', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/5273/'], u'cancelled': False, u'errored': True, u'wait_for': [], u'id': u'3068', u'resource_uri': u'/api/job/3068/'}

Step 5273 failed:
step_count: 4
console: 
description: Setting host profile on test001
class_name: SetHostProfileStep
backtrace: Communications error with test001.localdomain because session terminated
created_at: 2017-06-14T20:46:06.757344+00:00
args: {u'host': u'test001', u'server_profile': u'ServerProfile object'}
modified_at: 2017-06-14T20:46:11.345052+00:00
step_index: 0
state: failed
result: 
resource_uri: /api/step/5273/
id: 5273
log: 


--------------------- >> end captured stdout << ----------------------
```

**Comment by jgrund** [comment]
Simulator has been removed.
